### ISSUE TITLE
Add SubjectTypes to AssignmentListParams

### ISSUE THREAD

**Issue by RandolfTjandra** [brandur/wanikaniapi#2]
Might just be that the API has been recently, but there appears to be the ability to fetch assignments based on subject types which I don't see in the current version of AssignmentListParams

ref: https://docs.api.wanikani.com/20170710/#get-all-assignments

**Comment by brandur** [comment]
Released in v0.4.0.

**Comment by RandolfTjandra** [comment]
Awesome! Thanks man
